### ISSUE TITLE
Not or no longer on Melpa?

### ISSUE THREAD

**Issue by YellowOnion** [jstaursky/weyland-yutani-theme#1]
as said in title

**Comment by jstaursky** [comment]
Sorry I wasn't that active on github the time you posted this. I'm actually only just now seeing this, but yeah I'll look into it and update the theme within the next few days to make up for it.

**Comment by jstaursky** [comment]
In the meantime if your using something like spacemacs, here is how I load local packages not found in melpa
```elisp
  (use-package example
    :load-path "~/.spacemacs.d/local-packages/example-mode"
    :mode ("\\.ex\\'\\'" . example-mode)
    :commands example-mode)
```

**Comment by jstaursky** [comment]
Just finalized colors but going to take a little more time before submitting to melpa; I want the faces for different modes to appear consistent. I'm not really sure which ones are the most popular so if you have any suggestions please comment/send a pull request.

**Comment by jstaursky** [comment]
Took a bit longer than expected, but overall pretty happy with the way things look now. 

theme is now available in MELPA
